package com.moon.quizsnack

import com.moon.quizfruit.R

class Const {
    val thumbnail = arrayOf(
        R.drawable.apple,
        R.drawable.avocado,
        R.drawable.bae,
        R.drawable.banana,
        R.drawable.blueberry,
        R.drawable.boksunga,
        R.drawable.chamwe,
        R.drawable.chamwe,
        R.drawable.coconut,
        R.drawable.ddalgi,
        R.drawable.gam,
        R.drawable.ggingggang,
        R.drawable.guaba,
        R.drawable.gubong,
        R.drawable.gyul,
        R.drawable.hanrabong,
        R.drawable.hongsi,
        R.drawable.jadu,
        R.drawable.jamong,
        R.drawable.kiwe,
        R.drawable.laim,
        R.drawable.lemon,
        R.drawable.maesil,
        R.drawable.mango,
        R.drawable.melon,
        R.drawable.moga,
        R.drawable.muru,
        R.drawable.muwhagua,
        R.drawable.odi,
        R.drawable.orange,
        R.drawable.pineapple,
        R.drawable.podo,
        R.drawable.rambutan,
        R.drawable.salgu,
        R.drawable.subak,
        R.drawable.sukryu,
        R.drawable.tomato,
        R.drawable.youja
    )

    val name = arrayOf(
        "사과",
        "아보카도",
        "배",
        "바나나",
        "블루베리",
        "복숭아",
        "참외",
        "체리",
        "코코넛",
        "딸기",
        "감",
        "낑깡",
        "구아바",
        "거봉",
        "귤",
        "한라봉",
        "홍시",
        "자두",
        "자몽",
        "키위",
        "라임",
        "레몬",
        "매실",
        "망고",
        "멜론",
        "모과",
        "머루",
        "무화과",
        "오디",
        "오렌지",
        "파인애플",
        "포도",
        "람부탄",
        "살구",
        "수박",
        "석류",
        "토마토",
        "유자"
    )
}